[project]
name = "comp-par-labs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "KingPixelKP", email = "kingpixel2005@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.2",
    "matplotlib-inline>=0.2.2",
    "memory-profiler>=0.61.0",
    "pandas==2.*",
    "pyarrow>=25.0.1",
    "pyspark>=4.2.0",
    "tqdm>=4.70.1",
]

[project.scripts]
compar-spark-docker = "compar_spark_docker:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.4.0",
]

[tool.uv.workspace]
members = [
    "proj1",
]
