services:

  spark-master:
    image: spark:python3
    container_name: spark-master

    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master

    ports:
      - "8080:8080"
      - "7077:7077"


  spark-worker:
    image: spark:python3

    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
      --cores 2
      --memory 2G

    depends_on:
      - spark-master

    volumes: #Edit when add new lab
      - ../test-project/apps:/apps/test-project
      - ../test-project/data:/data/test-project

      - ../lab01/apps:/apps/lab01
      - ../lab01/data:/data/lab01

      - ../lab01/apps:/apps/lab02
      - ../lab01/data:/data/lab02

  jupyter:
    build:
      dockerfile: Dockerfile

    container_name: jupyter

    user: root

    environment:
      HOME: /tmp
      JUPYTER_CONFIG_DIR: /tmp/jupyter
      JUPYTER_RUNTIME_DIR: /tmp/jupyter/runtime
      JUPYTER_DATA_DIR: /tmp/jupyter/data
      JUPYTER_TOKEN: shared_spark_token # This is the notebook's password

    ports:
      - "8888:8888"

    volumes: #Edit when add new lab
      - ../test-project/notebooks:/workspace/test-project
      - ../test-project/data:/data/test-project

      - ../lab01/notebooks:/workspace/lab01
      - ../lab01/data:/data/lab01

      - ../lab01/notebooks:/workspace/lab02
      - ../lab01/data:/data/lab02

    working_dir: /workspace

    depends_on:
      - spark-master

    command: >
      jupyter lab
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --allow-root
